# Generated by Django 5.0.6 on 2024-09-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('product', '0011_alter_product_isavailable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(related_name='carts_where_this_exists', to='product.product'),
        ),
    ]
