# Generated by Django 5.0.6 on 2024-09-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_dateplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datePlaced',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
