# Generated by Django 5.0.6 on 2024-09-03 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_dateplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='datePlaced',
            new_name='date_placed',
        ),
    ]
