# Generated by Django 5.0.6 on 2024-09-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_rename_dateplaced_order_date_placed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('to_receive', 'to_receive'), ('received', 'received'), ('cancelled', 'cancelled')], default='to_receive', max_length=20),
        ),
    ]
