# Generated by Django 5.0.6 on 2024-08-27 11:40

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=product.models.construct_path)),
                ('description', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('isSold', models.BooleanField(default=False)),
            ],
        ),
    ]
