# Generated by Django 5.0.6 on 2024-08-27 12:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('378ff5b0-3809-4921-a79a-f1fcf562e1b2'), primary_key=True, serialize=False),
        ),
    ]
