# Generated by Django 5.0.6 on 2024-08-27 12:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9cee0ef2-4597-45e5-a8d5-518a168e60a8'), primary_key=True, serialize=False),
        ),
    ]
