# Generated by Django 5.0.6 on 2024-08-27 12:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6e75f0f0-972d-4952-94ed-d7ff53555160'), primary_key=True, serialize=False),
        ),
    ]
