# Generated by Django 5.0.6 on 2024-08-30 16:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_buyer_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('053a4d73-297d-4b99-9562-84d68bb83085'), primary_key=True, serialize=False, unique=True),
        ),
    ]
