# Generated by Django 5.0.6 on 2024-09-02 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='isSold',
            new_name='isAvailable',
        ),
        migrations.RemoveField(
            model_name='product',
            name='buyer',
        ),
    ]
