# Generated by Django 5.0.6 on 2024-09-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_rename_issold_product_isavailable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='isAvailable',
            field=models.BooleanField(default=True),
        ),
    ]
